sproutsocial/seeds-packets

packets/seedlings/src/_spacing.scss, packets/seedlings/src/_vertical-align.scss
Fixes a couple small inconsistencies with the utility classes we're using in marketing.
- Add missing space size to comments
- Update vertical align classes to include a few more
=> Sync seedlings classes with marketing utilities

packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/dist/seedlings-webapp.css, packets/seedlings/src/_whitespace.scss
- Fixes an issue where the white-space CSS classes are missing from the compiled CSS
- Builds the compiled CSS (missing from the last couple commits)
=> Fix mssing white space CSS

packets/seedlings/package.json
This will allow theming Seedlings (e.g. changing the primary and secondary brand colors) by setting variables and running Sass builds within consuming repos.
=> Add source files to package

packets/seedlings/src/_height.scss, packets/seedlings/src/axioms/Colors.scss
- Add missing min/max height utilities as well as none/auto
- Remove a couple of duplicate 100% height utils
- Remove the Google+ color from the Colors axiom
=> Fixes for height and network color utilities

package.json, packets/seeds-color/dist/seeds-color.xml, packets/seeds-networkcolor/dist/seeds-networkcolor.xml, yarn.lock
@benlister Just getting all of the dependencies up to date to prepare for the beta packages for Nectar
=> chore: update all dependencies to latest

packets/seedlings/dist/seedlings-adapt.css, packets/seedlings/dist/seedlings-bambu.css, packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/src/_animation.scss
- Adds new utility for our separated class that allows for box shadow instead of divs
- [WEB-439](https://sprout.atlassian.net/browse/WEB-439)
- [Test site](https://justin-test.stagely.sproutsocial.com/separated-test/)
=> [WEB-439] Add utility for our "separated" behavior using box shadow

packets/seedlings/dist/seedlings-adapt.css, packets/seedlings/dist/seedlings-bambu.css, packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/src/_shadow.scss
- We now have designs that account for shadows on mobile but are later unset on desktop, this fixes that
- [WEB-514](https://sprout.atlassian.net/browse/WEB-514)
- [Test site](https://justin-test.stagely.sproutsocial.com/shadow-test/?amp)
=> [WEB-514] Adds the ability to unset a shadow

packets/seedlings/dist/seedlings-adapt.css, packets/seedlings/dist/seedlings-bambu.css, packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/dist/seedlings-webapp.css, packets/seedlings/src/_border-width.scss, packets/seedlings/src/axioms/Border.scss
- Adds an 8px border width for Susan's new designs. This PR is mainly to check the CI integration done earlier.
- [Test site](https://justin-test.stagely.sproutsocial.com/border-width-test/)
=> Add larger border width for new designs

packets/seedlings/dist/seedlings-adapt.css, packets/seedlings/dist/seedlings-bambu.css, packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/dist/seedlings-webapp.css, packets/seedlings/src/_negative-margin.scss, packets/seedlings/src/_spacing.scss
* Adds 2 additional spacing sizes for padding and margin as well as 1 additional size for negative margins to better mimic our current row and column
- [WEB-781](https://sprout.atlassian.net/browse/WEB-781)
- [Test site](https://justin-test.stagely.sproutsocial.com/lps/sample-event/)
=> [WEB-781] Add additional sizes to seedlings spacing

packets/seedlings/dist/seedlings-adapt.css, packets/seedlings/dist/seedlings-bambu.css, packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/dist/seedlings-webapp.css, packets/seedlings/src/axioms/Colors.scss
- Adds all the missing `-0` colors to the Colors axiom (which build bg, border, and text colors)
- Main changes here: https://github.com/sproutsocial/seeds-packets/compare/BCT-1096?expand=1#diff-28c9f918511521d67bfe739d2b6fb4a3
- [BCT-1096](https://sprout.atlassian.net/browse/BCT-1096) - `teal-0` is included in this new page I'm currently working on.
=> [BCT-1096] Adding 0 colors to seedlings

packets/seedlings/dist/seedlings-adapt.css, packets/seedlings/dist/seedlings-bambu.css, packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/seedlings-marketing.scss, packets/seedlings/src/_line-height.scss, packets/seeds-typography/dist/seeds-typography.scss, packets/seeds-utils/style-dictionary/templates/typography-scss.hbs
* Adds a utility class for line heights to allow us to fix fine print using seeds typography values
- [BCT-3296](https://sprout.atlassian.net/browse/BCT-3296)
- [Test Site](https://marketing-test.stagely.sproutsocial.com/line-height-example/)
=> [BCT-3296] Add line height utility

packets/seedlings/yarn.lock, yarn.lock
* Updates outdated dependencies to resolve github security warnings
1. Pull down `dependency-upgrade` branch
1. Run `yarn` and `yarn build`
1. See there's no issues
=> [BCT-3527] Dependency upgrade

packets/seedlings/dist/seedlings-adapt.css, packets/seedlings/dist/seedlings-bambu.css, packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/dist/seedlings-webapp.css, packets/seedlings/seedlings-marketing.scss, packets/seedlings/src/_hide-scrollbar.scss
This PR adds a new utility to hide scrollbars.
=> [BCT-3456] Hide scrollbar utility

packets/seedlings/dist/seedlings-adapt.css, packets/seedlings/dist/seedlings-bambu.css, packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/dist/seedlings-webapp.css, packets/seedlings/src/_font-family.scss, packets/seeds-typography/dist/seeds-typography-unitless.js, packets/seeds-typography/dist/seeds-typography.css, packets/seeds-typography/dist/seeds-typography.js, packets/seeds-typography/dist/seeds-typography.scss, packets/seeds-typography/dist/tokens.json, packets/seeds-typography/tokens.json
* Add new Recoleta font util and family to typography
- [BCT-3590](https://sprout.atlassian.net/browse/BCT-3590)
=> [BCT-3590] Add new project stake typeface

packets/seedlings/dist/seedlings-marketing.css, packets/seeds-border/dist/seeds-border.css, packets/seeds-border/dist/seeds-border.js, packets/seeds-border/dist/seeds-border.scss, packets/seeds-border/dist/tokens.json
This is a fix #214  which didn't include built files
=> fix(build): commit built files

packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/src/axioms/Colors.scss
* Adds additional CSS utilities
- [BCT-3816](https://sprout.atlassian.net/browse/BCT-3816)
=> [BCT-3816] Adds additional network colors to our color utilities in seedlings

packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/src/_border-radius.scss, packets/seedlings/src/axioms/Border.scss
In this PR we are adding br1000 which already existed as a seed token [here](https://github.com/sproutsocial/seeds-packets/blob/develop/packets/seeds-border/tokens.json).
=> Adding br1000 utility

packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/src/_border-radius.scss
- Add a util to apply border radius to top-left and bottom-right to create a leaf frame pattern
- Include breakpoints for mobile and tablet/desktop to change the fixed values to maintain brand
Example use: https://staging.sproutsocial.com/agencies/agency-partner-program-application/
- Check that mobile serves `144px` border radius and desktop/tablet serves `167px`
- [BCT-4401](https://sprout.atlassian.net/browse/BCT-4401)
=> [BCT-4401] Add util for leaf frame

packets/seeds-networkcolor/tokens.json
We want to add Shopify as a color in the app.  I'm adding it as a network color.
=> Add Shopify network color

packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/seedlings-marketing.scss, packets/seedlings/src/_pointer-events.scss
* Looks like these were never made and just put into explicit style sheets, this adds the utility
- [BCT-5409](https://sprout.atlassian.net/browse/BCT-5409)
- [Test site](https://justin-test.stagely.sproutsocial.com/twitter-marketing/)
=> [BCT-5409] Add pointer event utility classes

packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/src/_spacing.scss, packets/seedlings/src/_square.scss
- Relates to: [MBCC-5708](https://sprout.atlassian.net/browse/MBCC-5708), dev task for Kickoff / Livestream viewing page.
- Added `size-675` to give 64px large (`(2 * $Space-size--500)`)
- Generated Updated Seedlings
=> MBCC-5708 New Size Utility

packets/seedlings/CHANGELOG.md, packets/seedlings/package.json
Update changelog from recent merges into main
=> Develop → Main

packets/seeds-depth/dist/seeds-depth.css, packets/seeds-depth/dist/seeds-depth.js, packets/seeds-depth/dist/seeds-depth.scss, packets/seeds-depth/dist/tokens.json
I didn't realize we include the `/dist` directory in git. This PR adds the new build to `seeds-depth/dist`  and should fix jenkins pipeline.
https://sprout.atlassian.net/browse/DAR-34?atlOrigin=eyJpIjoiOWRhNThjOGRlOGVhNGQyMzk4YmY2MTkwNThmOWU1NjYiLCJwIjoiaiJ9
=> DAR-34 - chore(seeds-depth): adding new build of seeds-depth package

packets/seeds-depth/dist/seeds-depth.css, packets/seeds-depth/dist/seeds-depth.js, packets/seeds-depth/dist/seeds-depth.scss, packets/seeds-depth/dist/tokens.json, packets/seeds-depth/tokens.json
Because we include the `/dist` directory I also need to add these changes to our main branch in order to deploy correctly. 
[- [SEEDS-](https://sprout.atlassian.net/browse/SEEDS-)](https://sprout.atlassian.net/browse/DAR-34?atlOrigin=eyJpIjoiOWRhNThjOGRlOGVhNGQyMzk4YmY2MTkwNThmOWU1NjYiLCJwIjoiaiJ9)
=> DAR-34 - Update seeds-depth build package

packets/seeds-depth/tokens.json
Removed depth 200 due to lack of usage
BREAKING CHANGE: replace depth 200 with depth 300
- Removed the depth 200 token
=> removed depth 200

packets/seeds-depth/dist/seeds-depth.css, packets/seeds-depth/dist/seeds-depth.js, packets/seeds-depth/dist/seeds-depth.scss, packets/seeds-depth/dist/tokens.json
I forgot to add the build output to this PR. 
- ran `yarn build` to include new package dist folder
=> chore: add new build

packets/seeds-depth/dist/seeds-depth.css, packets/seeds-depth/dist/seeds-depth.js, packets/seeds-depth/dist/seeds-depth.scss, packets/seeds-depth/dist/tokens.json, packets/seeds-depth/tokens.json
DAR-88 / Removing elevation200 from tokens list
- Removed elevation 200 from this package.
=> Update dist folder

packets/seedlings/CHANGELOG.md, packets/seedlings/package.json, packets/seeds-depth/CHANGELOG.md, packets/seeds-depth/package.json
DAR-88 / Removing elevation200 from tokens list
- Removed elevation 200 from this package
- Updated the `dist` folder that removes the above tokens
=> Removing the elevation 200 token

.github/CODEOWNERS, package.json, packets/seedlings/package.json, packets/seedlings/yarn.lock, packets/seeds-color/yarn.lock, yarn.lock
=> Merge develop into main

.github/CODEOWNERS, packets/seedlings/CHANGELOG.md, packets/seedlings/package.json, packets/seedlings/yarn.lock, packets/seeds-color/CHANGELOG.md, packets/seeds-color/package.json, packets/seeds-color/yarn.lock, packets/seeds-dataviz/CHANGELOG.md, packets/seeds-dataviz/package.json, yarn.lock
We were several commits behind on merging back into develop.
=> Merge main back into develop

package.json, yarn.lock
Upgrade Lerna to latest (5.1.2) to see if it resolves the lerna publish error happening[ here](https://jenkins01.int.sproutsocial.com/blue/organizations/jenkins/sproutsocial%2Fseeds-packets/detail/main/88/pipeline/70/) during build
- [SEEDS-](https://sprout.atlassian.net/browse/SEEDS-)
=> chore: upgrade lerna to 5.1.2

package.json, yarn.lock
-
- https://[YOUR GITHUB USER NAME HERE].github.io/seeds/
- [SEEDS-](https://sprout.atlassian.net/browse/SEEDS-)
=> upgrade lerna to 5.1.2

Dockerfile
-
- https://[YOUR GITHUB USER NAME HERE].github.io/seeds/
- [SEEDS-](https://sprout.atlassian.net/browse/SEEDS-)
=> chore: upgrade node version to 16

packets/seedlings/dist/seedlings-marketing.css, packets/seedlings/src/axioms/Colors.scss
* Adds tiktok's core branding (#000000) as well as their red variant to our Seedlings utilities
=> [MBC-10091] Add Tiktok colors to seedlings

package.json, yarn.lock
=> develop -> main

package.json
There was a small typo in the ci release step that failed
=> fix ci build error

package.json, yarn.lock
Removing this package resolution since it's not used by any package anymore.
=> add package resolution for parse-url

packages/seeds-tsconfig/base.json, packages/seeds-tsconfig/node16.json, packages/seeds-tsconfig/package.json, packages/seeds-tsconfig/react-library.json
Creates an internal package that can be where we write tsconfigs. 
This package is private and will not be published until we decide it's useful elsewhere.
=> Create private package to share tsconfigs across packages.

.changeset/neat-ducks-push.md, packages/seeds-border/config.json, packages/seeds-color/config.json, packages/seeds-depth/config.json, packages/seeds-motion/config.json, packages/seeds-networkcolor/config.json, packages/seeds-space/config.json, packages/seeds-typography/config.json, packages/seeds-utils/package.json, yarn.lock
- Major bumped style-dictionary to `v3` which comes with better typescript support
- Updates design token packages to utilize built-in javascript and typescript support
Jira: https://sprout.atlassian.net/browse/DS-1813
- [SEEDS-](https://sprout.atlassian.net/browse/SEEDS-)
=> [DS-1813]-Update Style-Dictionary and Update JS & TS transformations

.changeset/loud-weeks-battle.md, packages/eslint-config-seeds/index.js, packages/eslint-config-seeds/package.json, packages/seeds-tsconfig/package.json, packages/seeds-tsconfig/react-library.json, yarn.lock
Creating a sharable package would enable the design systems team to have a single source of truth
- Publishing `@sproutsocial/eslint-config-seeds`
- Publishing `@sproutsocial/seeds-tsconfig`
Jira: https://sprout.atlassian.net/browse/DS-1781
=> [DS-1781]- Publish custom Tsconfig and Eslint 
